export const cropImageMapper: Record<string, string> = {
  // 🌾 Cereals
  Jowar: "/uploads/Jowar.jpg",
  Sorghum: "/uploads/Jowar.jpg",
  Wheat: "/uploads/Wheat.jpg",
  Rice: "/uploads/Rice.jpg",
  Paddy: "/uploads/Paddy.jpg",
  Maize: "/uploads/Bajra(Millet).jpg",
  Corn: "/uploads/Bajra(Millet).jpg",

  // 🌻 Oil Seeds
  Soyabean: "/uploads/Soyabean.jpg",
  Mustard: "/uploads/Mustard.jpg",
  Groundnut: "/uploads/Ground Nut Seed.jpg",
  "Groundnut Pods": "/uploads/Groundnut Pods (Raw).jpg",
  Safflower: "/uploads/Safflower.jpg",
  Sunflower: "/uploads/Oil seeds.jpg",

  // 🫘 Pulses
  Tur: "/uploads/Tur.jpg",
  Arhar: "/uploads/Tur.jpg",
  Moong: "/uploads/Moong.jpg",
  Urad: "/uploads/Black Gram (Urad).jpg",
  Masoor: "/uploads/Lentil (Masoor).jpg",
  Rajma: "/uploads/Rajma (Kidney Bean).jpg",
  Chana: "/uploads/Chickpea Chana(Desi).jpg",
  "Kabuli Chana": "/uploads/Chickpea Chana (Kabuli).jpg",
  "Field Pea": "/uploads/Field Pea.jpg",
  Kulthi: "/uploads/Horse Gram (Kulthi).jpg",
  Cowpea: "/uploads/Cowpea (Lobia  Chawli).jpg",
  Lobia: "/uploads/Cowpea (Lobia  Chawli).jpg",
  Avare: "/uploads/Green Avare (W).png",
  "Pigeon Pea": "/uploads/Pigeon Pea (TUR).jpg",

  // 🧵 Fibre Crops
  Cotton: "/uploads/cotton.jpg",
  Jute: "/uploads/Jute.jpg",
  Sugarcane: "/uploads/Sugarcane.jpg",

  // 🥦 Vegetables
  Onion: "/uploads/Onion.jpg",
  Potato: "/uploads/Potato.jpg",
  Tomato: "/uploads/Tomato.png",
  Cabbage: "/uploads/Cabbage.png",
  Carrot: "/uploads/Carrot.png",
  Cauliflower: "/uploads/Cauliflower.png",
  Pumpkin: "/uploads/Pumpkin.png",
  Capsicum: "/uploads/Capsicum.png",
  Ridgegourd: "/uploads/Ridgegourd (Tori).png",
  Brinjal: "/uploads/Brinjal.jpg",
  "Bitter Gourd": "/uploads/Bitter Gourd.jpg",
  "Bottle Gourd": "/uploads/Bottle Gourd.jpg",
  "Cluster Beans": "/uploads/Cluster Beans (Guar).jpg",
  Drumstick: "/uploads/Drumstick.jpg",
  Cucumber: "/uploads/Cucumber (Kheera).jpg",
  Spinach: "/uploads/Spinach.png",

  // 🍉 Fruits
  Banana: "/uploads/Banana.jpg",
  Apple: "/uploads/Apple.jpg",
  Mango: "/uploads/Mango.jpg",
  Grapes: "/uploads/Grapes.jpg",
  Orange: "/uploads/Orange.jpg",
  Pomegranate: "/uploads/Pomegranate.jpg",
  Guava: "/uploads/Guava.jpg",
  Lemon: "/uploads/Lemon.jpg",
  Papaya: "/uploads/Papaya.jpg",
  "Water Melon": "/uploads/Water Melon.jpg",
  "Sweet Lime": "/uploads/Mousambi (Sweet Lime).jpg",
  Pineapple: "/uploads/Pineapple.jpg",
  Kinnow: "/uploads/Kinnow.jpg",
  "Musk Melon": "/uploads/Karbuja (Musk Melon).jpg",
};
